### ISSUE TITLE
unable to load python app

### ISSUE THREAD

**Issue by furkankav** [LexPredict/lexpredict-contraxsuite#15]
I've got this error in uwsgi log file unable to load app 0 (mountpoint='') (callable not found or import error)

**Comment by ericlex** [comment]
hello @furkankav - Can you provide more information? Where are you having the issue? Do you have the application installed?

We're unable to troubleshoot the problem you're facing without further information.

**Comment by furkankav** [comment]
Here is what I have in uwsgi log 
*** starting uWSGI Emperor ***
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 4
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Set PythonHome to /opt/ve
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9e62e60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/opt/ve/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "analyze_textunitclassifier" does not exist
LINE 1: ...t", "analyze_textunitclassifier"."is_active" FROM "analyze_t...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./wsgi.py", line 29, in <module>
    application = get_wsgi_application()
  File "/opt/ve/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/opt/ve/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/opt/ve/lib/python3.5/site-packages/django/core/handlers/base.py", line 80, in load_middleware
    middleware = import_string(middleware_path)
  File "/opt/ve/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./apps/common/middleware.py", line 28, in <module>
    EXEMPT_URLS = [re_compile(settings.LOGIN_URL.lstrip('/'))]
  File "/opt/ve/lib/python3.5/site-packages/django/utils/functional.py", line 114, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/opt/ve/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/opt/ve/lib/python3.5/site-packages/django/urls/resolvers.py", line 436, in _reverse_with_prefix
    self._populate()
 File "/opt/ve/lib/python3.5/site-packages/django/urls/resolvers.py", line 288, in _populate
    for pattern in reversed(self.url_patterns):
  File "/opt/ve/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/ve/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/ve/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/ve/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./urls.py", line 39, in <module>
    url(r'^document/', include('apps.document.urls', namespace='document')),
  File "/opt/ve/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./apps/document/urls.py", line 11, in <module>
    from apps.document import views
  File "./apps/document/views.py", line 42, in <module>
    from apps.task.views import TaskListView
  File "./apps/task/views.py", line 18, in <module>
    from apps.task.forms import (
  File "./apps/task/forms.py", line 257, in <module>
   class ExistedClassifierClassifyForm(forms.Form):
  File "./apps/task/forms.py", line 260, in ExistedClassifierClassifyForm
    choices=[(c.pk, c.name) for c in TextUnitClassifier.objects.filter(is_active=True)],
  File "/opt/ve/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/ve/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/ve/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
  File "/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ve/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ve/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ve/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ve/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "analyze_textunitclassifier" does not exist
LINE 1: ...t", "analyze_textunitclassifier"."is_active" FROM "analyze_t...
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20445)
spawned uWSGI worker 1 (pid: 20453, cores: 1)
spawned uWSGI worker 2 (pid: 20454, cores: 1)
spawned uWSGI worker 3 (pid: 20455, cores: 1)
spawned uWSGI worker 4 (pid: 20456, cores: 1)
spawned uWSGI worker 5 (pid: 20457, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 20455|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 599 bytes} [Thu Dec  7 16:47:44 2017] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20455|app: -1|req: -1/2] 127.0.0.1 () {42 vars in 651 bytes} [Thu Dec  7 16:47:46 2017] GET /home => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20455|app: -1|req: -1/3] 127.0.0.1 () {42 vars in 651 bytes} [Thu Dec  7 16:47:50 2017] GET /home => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20455|app: -1|req: -1/4] 127.0.0.1 () {40 vars in 612 bytes} [Thu Dec  7 16:47:55 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20455|app: -1|req: -1/5] 127.0.0.1 () {42 vars in 643 bytes} [Thu Dec  7 16:47:58 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20455|app: -1|req: -1/6] 127.0.0.1 () {42 vars in 643 bytes} [Thu Dec  7 16:47:59 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[emperor] *** RAGNAROK EVOKED ***
SIGINT/SIGQUIT received...killing workers...
Thu Dec  7 11:19:48 2017 - The Emperor is buried.
The Emperor has been buried (pid: 20446)
