### ISSUE TITLE
Error on loading common legal terms

### ISSUE THREAD

**Issue by dwmcqueen** [LexPredict/lexpredict-contraxsuite#20]
Ran the admin task to load common legal terms and got this error:

INFO 2018-01-15 18:03:51,325 | Parse "https://raw.githubusercontent.com/LexPredict/lexpredict-legal-dictionary/1.0.5/en/legal/common_law_top1000.csv"
ERROR 2018-01-15 18:03:51,387 | ERROR
ERROR 2018-01-15 18:03:51,393 | HTTPError: HTTP Error 404: Not Found
ERROR 2018-01-15 18:03:51,395 | Traceback (most recent call last):
File "/opt/lexpredict-contraxsuite/contraxsuite_services/apps/task/tasks.py", line 208, in run
self.process(**kwargs)
File "/opt/lexpredict-contraxsuite/contraxsuite_services/apps/task/tasks.py", line 469, in process
data = pd.read_csv(path)
File "/opt/ve/lib/python3.5/site-packages/pandas/io/parsers.py", line 705, in parser_f
return _read(filepath_or_buffer, kwds)
File "/opt/ve/lib/python3.5/site-packages/pandas/io/parsers.py", line 429, in _read
filepath_or_buffer, encoding, compression)
File "/opt/ve/lib/python3.5/site-packages/pandas/io/common.py", line 190, in get_filepath_or_buffer
req = _urlopen(filepath_or_buffer)
File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.5/urllib/request.py", line 472, in open
response = meth(req, response)
File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.5/urllib/request.py", line 510, in error
return self._call_chain(*args)
File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
result = func(*args)
File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

INFO 2018-01-15 18:03:51,399 | End of main task "Load Terms", id=3
INFO 2018-01-15 18:03:51,401 | There are 1 uncompleted subtasks remaining. Please wait.

**Comment by dwmcqueen** [comment]
This commit should fix it #17

**Comment by dwmcqueen** [comment]
Fixed with recent commit.
