### ISSUE TITLE
Missing `contrax_frontend` in latest release

### ISSUE THREAD

**Issue by harshsuri** [LexPredict/lexpredict-contraxsuite#38]
Referring to issues #37 and #35 , it appears the frontend artifact is not included in the release.  Also, no documentation were found which would mention any workarounds to make the application work.

**Comment by harshsuri** [comment]
Adding further description.  Following the steps on a fresh Ubuntu LTS 16.04, all services and containers are up.

![image](https://user-images.githubusercontent.com/5026685/45269605-ebc0b280-b45e-11e8-9125-54d5fc02608a.png)

Next, logging into the Nginx container bash shell

![image](https://user-images.githubusercontent.com/5026685/45269631-435f1e00-b45f-11e8-9463-4f20de79cabf.png)

Checking the folder structure:

![image](https://user-images.githubusercontent.com/5026685/45269638-596cde80-b45f-11e8-8c5a-2446675c396c.png)

The `contraxtsuite_services` folder is populated per the dockerfile

![image](https://user-images.githubusercontent.com/5026685/45269647-891be680-b45f-11e8-9702-8398076719f5.png)

and

![image](https://user-images.githubusercontent.com/5026685/45269652-9b962000-b45f-11e8-8496-2a288be89790.png)

The `contraxsuite_frontend` folder is empty

![image](https://user-images.githubusercontent.com/5026685/45269664-c54f4700-b45f-11e8-8ead-a1f37fb5e85a.png)

**Comment by talalzahid91** [comment]
@harshsuri  Did you place the theme and jqwidget files at the proper location before running the script?

**Comment by harshsuri** [comment]
hi @talalzahid91 , yes I did place them in the  `dependencies` folder.

**Comment by talalzahid91** [comment]
@harshsuri  I am having the same issue. Now, I am trying using without the docker approach i.e by using deployment script. However, I have tried it before and it does not work. I am going to debug it. I guess there is either problem with the development guide or with the code but the people who are developing it seems like not to care.

**Comment by talalzahid91** [comment]
@ericlex  thanks for the reply.

**Comment by talalzahid91** [comment]
@harshsuri That fix seems to be different.

**Comment by ggndtes** [comment]
Hi All, just to mention I am experiencing the same issue and I am looking forward to suggestion from the dev team.

Just to confirm, which 'theme-example.zip' file did you place in the dependencies folder before running the script? I used the one from the following commit: https://github.com/LexPredict/lexpredict-contraxsuite/commit/2f67eadeb4c553ee7b1a83b6ef6daab2114ef0db.

Thanks all for helping.

**Comment by ericlex** [comment]
@harshsuri @talalzahid91 @ggndtes - Please try to re-run this and

**Comment by ericlex** [comment]
Also - We're updating the readme and setup script to obtain and apply SSL an SSL Certificate from LetsEncrypt

**Comment by harshsuri** [comment]
thank @ericlex .  I tried the docker deployment and the UI was up and running.  Next, I uploaded a sample PDF using the `Browse/Upload Documents` task after creating a new folder `test` which was successful.  Further, using the admin task I tried to load the document giving the path as `test` for a project `test` and kept the rest of fields default blank.  I received the following error:

`Main task: 969f4c25-446d-4a17-bf26-b84f971d4038 | Sub-task: 969f4c25-446d-4a17-bf26-b84f971d4038`
`INFO 2018-09-14 19:11:27 | Celery task id: 969f4c25-446d-4a17-bf26-b84f971d4038`

`Main task: 969f4c25-446d-4a17-bf26-b84f971d4038 | Sub-task: 969f4c25-446d-4a17-bf26-b84f971d4038`
`INFO 2018-09-14 19:11:27 | Start task "Load Documents", id=None
Kwargs: {'task_id': '969f4c25-446d-4a17-bf26-b84f971d4038', 'user_id': 1, 'metadata': {'result_links': [{'link': 'document:document-list', 'name': 'View Document List'}, {'link': 'document:text-unit-list', 'name': 'View Text Unit List'}]}, 'delete': False, 'source_path': 'test', 'source_type': '', 'detect_contract': True, 'project': , 'document_type': None, 'run_standard_locators': False}`
`Main task: 969f4c25-446d-4a17-bf26-b84f971d4038 | Sub-task: 969f4c25-446d-4a17-bf26-b84f971d4038`
`INFO 2018-09-14 19:11:27 | End of main task "Load Documents", id=None. Sub-tasks may be still running.`
`Main task: 969f4c25-446d-4a17-bf26-b84f971d4038 | Sub-task: 969f4c25-446d-4a17-bf26-b84f971d4038`
`ERROR 2018-09-14 19:11:27 | Task has been failed:
Load Documents
Args: ()
Kwargs: {'task_id': '969f4c25-446d-4a17-bf26-b84f971d4038', 'user_id': 1, 'metadata': {'result_links': [{'link': 'document:document-list', 'name': 'View Document List'}, {'link': 'document:text-unit-list', 'name': 'View Text Unit List'}]}, 'source_type': '', 'project': , 'source_path': 'test', 'detect_contract': True, 'delete': False, 'document_type': None, 'run_standard_locators': False}
Reason: 'source_data'
Traceback (most recent call last):
File "/contraxsuite_services/apps/task/tasks.py", line 287, in __call__
return super().__call__(*args, **kwargs)
File "/contraxsuite_services/venv/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/contraxsuite_services/apps/task/tasks.py", line 400, in run
ret = self.process(**kwargs)
File "/contraxsuite_services/apps/task/tasks.py", line 423, in process
path = kwargs['source_data']
KeyError: 'source_data'`

`Main task: 969f4c25-446d-4a17-bf26-b84f971d4038 | Sub-task: 969f4c25-446d-4a17-bf26-b84f971d4038`
`INFO 2018-09-14 19:11:27 | Traceback:
Traceback (most recent call last):
File "/contraxsuite_services/venv/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/contraxsuite_services/apps/task/tasks.py", line 297, in __call__
raise exc
File "/contraxsuite_services/apps/task/tasks.py", line 287, in __call__
return super().__call__(*args, **kwargs)
File "/contraxsuite_services/venv/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/contraxsuite_services/apps/task/tasks.py", line 400, in run
ret = self.process(**kwargs)
File "/contraxsuite_services/apps/task/tasks.py", line 423, in process
path = kwargs['source_data']
KeyError: 'source_data'`

`Main task: 969f4c25-446d-4a17-bf26-b84f971d4038 | Sub-task: 969f4c25-446d-4a17-bf26-b84f971d4038
ERROR 2018-09-14 19:11:37 | Load Documents #969f4c25-446d-4a17-bf26-b84f971d4038: some/all of sub-tasks have been crashed`
