### ISSUE TITLE
Uploading and processing documents

### ISSUE THREAD

**Issue by alexanderjulmer** [LexPredict/lexpredict-contraxsuite#6]
I am trying to process a PDF document but I seem to be out of luck. I created a new folder (via "Browse/Upload Documents" called `test` and uploaded a PDF document into it. 

I guess that next I have to run an admin task (via "Admin Tasks") to move the document inside the document engine. So I did: 

1. Run Task
1. Load Data
1. Load Documents
1. Source path `test`
1. Source Type `Document`(?)
1. Document Type `pdf`
1. Unchecked `Delete existing Documents`
1. Load

The task is now pending for some minutes with no progress shown. What could it be?

**Comment by mjbommar** [comment]
Hello @alexanderjulmer , thanks for your question.  If you are more comfortable sharing sensitive details by email, please reach out at support@contraxsuite.com.

1. Did your task complete eventually?  For large or complex PDFs, the OCR engine may take some time to complete, especially on a laptop.

2. Can you please share a copy of the log from the Task Details?

![image](https://user-images.githubusercontent.com/85053/30393855-60585ae0-988f-11e7-9892-0656cda146f1.png)

![image](https://user-images.githubusercontent.com/85053/30393868-69cfc572-988f-11e7-8c72-a942d181a114.png)

![image](https://user-images.githubusercontent.com/85053/30393909-82695c10-988f-11e7-8351-f77f16cd2d63.png)

3. Would you be able to share the actual PDF in question?  You can share with us at support@contraxsuite.com as well.

**Comment by alexanderjulmer** [comment]
The task is still pending 13 minutes in (I paused the VM at some point and restarted it now). It was just a one page, 100KB file. Nothing complex, really. 

Weirdly, there is no log. Maybe I made a mistake setting up the ContraxSuite?

<img width="1262" alt="bildschirmfoto 2017-09-13 um 20 33 45" src="https://user-images.githubusercontent.com/10468332/30394255-dff599f6-98c2-11e7-8ed2-695b2de648f1.png">

I originally used this file: 

[Entwurf Sachbericht.pdf](https://github.com/LexPredict/lexpredict-contraxsuite/files/1300432/Entwurf.Sachbericht.pdf)

But since this had all the markup, I tried again with this document, but again, no luck (also no log):

[Übungsverfahren Beschluss.pdf](https://github.com/LexPredict/lexpredict-contraxsuite/files/1300436/Ubungsverfahren.Beschluss.pdf)

**Comment by alexanderjulmer** [comment]
```
~$ tesseract --version
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0
```

But I tried to restart celery and got:

```
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 18, in <module>
    main()
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/ve/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'apps'
	> celery1@alex-contrax: * Child terminated with exit code 1
FAILED
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 18, in <module>
    main()
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/ve/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'apps'
	> celery2@alex-contrax: * Child terminated with exit code 1
FAILED
(ve) alex@alex-contrax:~$ celery multi start 2 -A apps.task -B -f celery.log
celery multi v4.0.2 (latentcall)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 18, in <module>
    main()
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/ve/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'apps'
	> celery1@alex-contrax: * Child terminated with exit code 1
FAILED
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 18, in <module>
    main()
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/opt/ve/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/ve/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'apps'
	> celery2@alex-contrax: * Child terminated with exit code 1
FAILED
```

**Comment by mjbommar** [comment]
Can you please try running this `celery` command from the `$PROJECT/contraxsuite_services`/ path?  Please see this section of the [Administration Guide for Linux](https://github.com/LexPredict/lexpredict-contraxsuite/blob/1.0.1/documentation/Installation%20and%20Administration%20Documentation/Administration%20Guide%20for%20Linux.pdf):

![image](https://user-images.githubusercontent.com/85053/30396294-25488d6e-9897-11e7-91db-f70fe8019910.png)

Also, can you please review your `$PROJECT/contraxsuite_services/celery.log` file for details of the task ID.  You should see something like this:

```
INFO    2017-09-13 18:57:56,095 | Start task "Load Documents", id=100
[2017-09-13 18:57:56,095: INFO/PoolWorker-4] LoadDocuments[0c0ec3e7-5a20-4887-9ac4-c5bf89416b32]: Start task "Load Documents", id=100
INFO    2017-09-13 18:57:56,098 | Parse /opt/lexpredict-contraxsuite-services/contraxsuite_services/media/data/documents/github_issue_6
[2017-09-13 18:57:56,098: INFO/PoolWorker-4] LoadDocuments[0c0ec3e7-5a20-4887-9ac4-c5bf89416b32]: Parse /opt/lexpredict-contraxsuite-services/contraxsuite_services/media/data/documents/github_issue_6
INFO    2017-09-13 18:57:56,100 | Detected 1 files. Added 1 subtasks.
[2017-09-13 18:57:56,100: INFO/PoolWorker-4] LoadDocuments[0c0ec3e7-5a20-4887-9ac4-c5bf89416b32]: Detected 1 files. Added 1 subtasks.
INFO    2017-09-13 18:57:56,140 | End of main task "Load Documents", id=100
[2017-09-13 18:57:56,140: INFO/PoolWorker-4] LoadDocuments[0c0ec3e7-5a20-4887-9ac4-c5bf89416b32]: End of main task "Load Documents", id=100
[2017-09-13 18:57:56,140: INFO/MainProcess] Received task: apps.task.tasks.create_document[100_dde06077-ef70-4c26-8cdf-afee3e672b0a]
INFO    2017-09-13 18:57:56,144 | There are 1 uncompleted subtasks remaining. Please wait.
[2017-09-13 18:57:56,144: INFO/PoolWorker-4] LoadDocuments[0c0ec3e7-5a20-4887-9ac4-c5bf89416b32]: There are 1 uncompleted subtasks remaining. Please wait.
[2017-09-13 18:57:56,149: INFO/PoolWorker-4] Task LoadDocuments[0c0ec3e7-5a20-4887-9ac4-c5bf89416b32] succeeded in 0.06006839871406555s: 'ok'
[2017-09-13 18:57:57,179: WARNING/PoolWorker-4] 0.003367003367003367
[2017-09-13 18:57:57,180: WARNING/PoolWorker-4] 0.05555555555555555
...
...
...
[2017-09-13 18:57:57,184: WARNING/PoolWorker-4] 18
[2017-09-13 18:57:57,184: WARNING/PoolWorker-4] 2
[2017-09-13 18:57:57,184: WARNING/PoolWorker-4] 1
INFO    2017-09-13 18:57:57,229 | LOADED (TIKA): /opt/lexpredict-contraxsuite-services/contraxsuite_services/media/data/documents/github_issue_6/Entwurf.Sachbericht.pdf
[2017-09-13 18:57:57,229: INFO/PoolWorker-4] apps.task.tasks.create_document[100_dde06077-ef70-4c26-8cdf-afee3e672b0a]: LOADED (TIKA): /opt/lexpredict-contraxsuite-services/contraxsuite_services/media/data/documents/github_issue_6/Entwurf.Sachbericht.pdf
[2017-09-13 18:57:57,236: INFO/PoolWorker-4] Task apps.task.tasks.create_document[100_dde06077-ef70-4c26-8cdf-afee3e672b0a] succeeded in 1.0941441105678678s: None
```

**Comment by alexanderjulmer** [comment]
Sorry, I am an idiot. I read this three times today, did it wrong every time and forgot it again. Works fine from the correct path.

**Comment by alexanderjulmer** [comment]
The error with celery was my mistake. I read that three times today and forgot it again. Works fine from the right directory.

Here's my celery log:

```
_gdbm.error: [Errno 11] Resource temporarily unavailable
[2017-09-12 16:37:59,266: INFO/MainProcess] mingle: all alone
[2017-09-12 16:37:59,293: INFO/MainProcess] celery1@alex-contrax ready.
[2017-09-12 16:37:59,424: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2017-09-12 16:37:59,439: INFO/MainProcess] mingle: searching for neighbors
[2017-09-12 16:37:59,463: INFO/MainProcess] sync with celery2@alex-contrax
[2017-09-12 16:38:00,467: INFO/MainProcess] mingle: sync with 1 nodes
[2017-09-12 16:38:00,468: INFO/MainProcess] mingle: sync complete
[2017-09-12 16:38:00,478: INFO/MainProcess] celery2@alex-contrax ready.
[2017-09-12 16:41:28,217: INFO/MainProcess] beat: Shutting down...
[2017-09-12 16:41:28,285: INFO/MainProcess] beat: Shutting down...
INFO    2017-09-13 11:44:10,615 | Task "Purge task", app task id=1
INFO    2017-09-13 11:44:10,620 | Celery task id=8c7557c9-10f7-45dd-a88a-392b7d86e$
INFO    2017-09-13 11:44:12,778 | Deleted task, celery task, 0 children celery tas$
INFO    2017-09-13 11:47:12,460 | Task "Purge task", app task id=2
INFO    2017-09-13 11:47:12,461 | Celery task id=1a985ef1-df6f-467f-8499-e2ce7bf5b$
INFO    2017-09-13 11:47:14,530 | Deleted task, celery task, 0 children celery tas$
INFO    2017-09-13 11:53:35,128 | Task "Purge task", app task id=3
INFO    2017-09-13 11:53:35,130 | Celery task id=6d5ef333-227e-4a27-947e-80dbd9e0b$
INFO    2017-09-13 11:53:37,346 | Deleted task, celery task, 0 children celery tas$
INFO    2017-09-13 11:53:38,985 | Task "Purge task", app task id=4
INFO    2017-09-13 11:53:38,987 | Celery task id=48db9360-16d5-4b50-ae06-973f2e2a6$
INFO    2017-09-13 11:53:41,070 | Deleted task, celery task, 0 children celery tas$
INFO    2017-09-13 19:28:02,625 | Task "Purge task", app task id=6
INFO    2017-09-13 19:28:02,626 | Celery task id=20f4d676-9ab9-4a87-8d89-b12950aea$
INFO    2017-09-13 19:28:04,646 | Deleted task, celery task, 0 children celery tas$
INFO    2017-09-13 19:28:05,349 | Task "Purge task", app task id=5
INFO    2017-09-13 19:28:05,350 | Celery task id=b917bcd0-285c-41c3-9fbc-bc4a6107c$
INFO    2017-09-13 19:28:07,564 | Deleted task, celery task, 0 children celery tas$
```

What confuses me is the lack of any entry for starting a task (Timezone is UTC+1:00).

**Comment by mjbommar** [comment]
Do you seen any pending/active tasks when you run `celery -A apps.task inspect active`?  Have you tried running `celery -A apps.task purge` yet too?

Also, can you list the upload directory with ownership/permissions like this:
`ls -lht $PROJECT/contraxsuite_services/media/data/documents/`

**Comment by alexanderjulmer** [comment]
```
(ve) alex@alex-contrax:/opt/lexpredict-contraxsuite/contraxsuite_services$  celery -A apps.task inspect active
```
```
/opt/ve/lib/python3.5/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/opt/ve/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 285, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 367, in handle_argv
    *self.parse_options(prog_name, argv, command))
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 403, in parse_options
    self.parser = self.create_parser(prog_name, command)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 413, in create_parser
    epilog=self._format_epilog(self.epilog),
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/control.py", line 167, in epilog
    self.list_commands(indent=4, help=True, app=self.app)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/control.py", line 56, in list_commands
    choices = cls._choices_by_group(app)
  File "/opt/ve/lib/python3.5/site-packages/celery/bin/control.py", line 152, in _choices_by_group
    app.loader.import_default_modules()
  File "/opt/ve/lib/python3.5/site-packages/celery/loaders/base.py", line 111, in import_default_modules
    return [self.import_task_module(m) for m in self.default_modules]
  File "/opt/ve/lib/python3.5/site-packages/celery/loaders/base.py", line 111, in <listcomp>
    return [self.import_task_module(m) for m in self.default_modules]
  File "/opt/ve/lib/python3.5/site-packages/celery/loaders/base.py", line 97, in import_task_module
    return self.import_from_cwd(module)
  File "/opt/ve/lib/python3.5/site-packages/celery/loaders/base.py", line 106, in import_from_cwd
    package=package,
  File "/opt/ve/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/opt/ve/lib/python3.5/site-packages/celery/loaders/base.py", line 100, in import_module
    return importlib.import_module(module, package=package)
  File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/lexpredict-contraxsuite/contraxsuite_services/apps/task/tasks.py", line 39, in <module>
    from apps.task.utils.nlp import lang
  File "/opt/lexpredict-contraxsuite/contraxsuite_services/apps/task/utils/nlp/lang.py", line 4, in <module>
    import tika.language
  File "/opt/ve/lib/python3.5/site-packages/tika/language.py", line 19, in <module>
    from .tika import detectLang1, callServer, ServerEndpoint
  File "/opt/ve/lib/python3.5/site-packages/tika/tika.py", line 108, in <module>
    fileHandler = logging.FileHandler(log_file)
  File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/tika.log'
````

```
(ve) alex@alex-contrax:/opt/lexpredict-contraxsuite/contraxsuite_services$ ls -lht media/data/documents/
```

```
total 8.0K
drwxr-xr-x 2 root root 4.0K Sep 13 14:13 testB
drwxr-xr-x 2 root root 4.0K Sep 13 13:53 test
```

**Comment by mjbommar** [comment]
Do you know if the installation script was run using the `root` user?  
![image](https://user-images.githubusercontent.com/85053/30398176-719c7ce2-989d-11e7-99a8-68d95732ff8d.png)


We generally recommend that you run as non-root, unless you intend to switch all services over to run under the `root` account as well.  It seems like `tika` is failing to start, which would interrupt the `celery` workflow.

Can you try the following steps:
```
$ sudo chown ubuntu:ubuntu /tmp/tika.log
$ sudo chown -R ubuntu:ubuntu /opt/lexpredict-contraxsuite/
```

Then try purging the pending tasks, restarting celery, and then re-submitting the Load Document task.

**Comment by alexanderjulmer** [comment]
That did the trick. It's possible indeed that I ran  `setup_local.sh` as root. My bad. Sorry for the unnecessary trouble.

**Comment by mjbommar** [comment]
No problem!  Were you able to successfully upload and parse the PDF?

We'll make sure to incorporate your feedback into the documentation for 1.0.2.  Would a larger "call-out" or "warning" box have been helpful for some of these steps, like the non-root user or the `celery` execution paths?

**Comment by alexanderjulmer** [comment]
Yeah, parsing worked just fine. I'll try some contracts tomorrow. 

I'll open a new issue for the installation instructions.
